### ISSUE TITLE
Local Path Issue?

### ISSUE THREAD

**Issue by xlxcomputer** [lilakk/PostMark#1]
Thanks for your amazing work in black-box watermark.However,I find some issue in your code.
In   PostMark/postmark/models.py，class Llama3_8B().  "/work/pi_miyyer_umass_edu/LLMs/Meta-Llama-3-8B" maybe is a local path for your llm model?

OSError: Incorrect path_or_model_id: '/work/pi_miyyer_umass_edu/LLMs/Meta-Llama-3-8B'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

**Comment by lilakk** [comment]
Thank you for pointing this out! Yes the code is using a local path to the model, I've just pushed some changes to fix this issue.
